import { toPng } from "html-to-image";
import jsPDF from "jspdf";

/**
 * Reusable PDF export hook
 * - Zone-based watermark (no overlap with text)
 * - Professional footer with date
 * - Full-height capture
 */
export function usePdfExport() {

    // ---------- helper: convert image to base64 ----------
    const fetchImageAsDataUrl = async (url) => {
        try {
            const res = await fetch(url, { mode: "cors" });
            const blob = await res.blob();
            return new Promise((resolve) => {
                const reader = new FileReader();
                reader.onloadend = () => resolve(reader.result);
                reader.readAsDataURL(blob);
            });
        } catch (err) {
            console.warn("Image fetch failed:", err);
            return url;
        }
    };

    const addZoneWatermark = (pdf, text = "lifepage.in") => {
        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();

        // Brand color: amber-600
        pdf.setTextColor(217, 119, 6);
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(20);
        

        const zones = [

            { x: pageWidth / 5, y: pageHeight * 0.08 },

            // Space before career plan section
            { x: pageWidth / (10 / 4), y: pageHeight * 0.40 },

            // Middle gap between sections
            { x: pageWidth / (10/6), y: pageHeight * 0.57 },

            // Bottom background area
            { x: pageWidth / (10 / 9), y: pageHeight * 0.9 },
        ];

        zones.forEach((zone) => {
            pdf.text(text, zone.x, zone.y, {
                align: "center",
                angle: -20,
                opacity: 0.045,
            });
        });
    };

    // ---------- FOOTER ----------
    const addFooter = (pdf, options = {}) => {
        const {
            brand = "lifepage.in",
            generatedFor,
        } = options;

        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();

        const date = new Date().toLocaleDateString("en-GB", {
            day: "2-digit",
            month: "short",
            year: "numeric",
        });

        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(11);      // print-safe
        pdf.setTextColor(100);    // dark gray

        const y = pageHeight - 12;

        // Left
        pdf.text(`Generated by ${brand}`, 12, y);

        // Center
        pdf.text(date, pageWidth / 2, y, { align: "center" });

        // Right
        if (generatedFor) {
            pdf.text(
                `Prepared for: ${generatedFor}`,
                pageWidth - 12,
                y,
                { align: "right" }
            );
        }
    };

    // ---------- MAIN EXPORT ----------
    const exportPdf = async ({
        ref,
        fileName = "download",
        background = "bg_image.png",
        watermarkText = "lifepage.in",
        imageSelector = "img",
        generatedFor,
    }) => {
        if (!ref?.current) return;

        const el = ref.current;

        const originalStyles = {
            backgroundImage: el.style.backgroundImage,
            backgroundSize: el.style.backgroundSize,
            backgroundPosition: el.style.backgroundPosition,
            backgroundRepeat: el.style.backgroundRepeat,
        };

        try {
            // Apply PDF-only background
            if (background) {
                el.style.backgroundImage = `url('${background}')`;
                el.style.backgroundSize = "cover";
                el.style.backgroundPosition = "center";
                el.style.backgroundRepeat = "no-repeat";
            }

            // Fix image CORS
            const images = el.querySelectorAll(imageSelector);
            for (const img of images) {
                if (img.src && !img.src.startsWith("data:")) {
                    img.src = await fetchImageAsDataUrl(img.src);
                }
            }

            const dataUrl = await toPng(el, {
                backgroundColor: "#ffffff",
                pixelRatio: 3,
                cacheBust: true,
                height: el.scrollHeight,
            });

            const img = new Image();
            img.src = dataUrl;
            await new Promise((res) => (img.onload = res));

            const pxToMm = (px) => px * 0.264583;
            const pdfWidth = pxToMm(img.width);
            const pdfHeight = pxToMm(img.height);

            const pdf = new jsPDF({
                orientation: pdfWidth > pdfHeight ? "landscape" : "portrait",
                unit: "mm",
                format: [pdfWidth, pdfHeight],
            });

            // Add content image
            pdf.addImage(dataUrl, "PNG", 0, 0, pdfWidth, pdfHeight);

            // Add watermark ONLY in safe zones
            addZoneWatermark(pdf, watermarkText);

            // Add footer
            addFooter(pdf, { generatedFor });

            pdf.save(`${fileName}.pdf`);
        } catch (err) {
            console.error("PDF export failed", err);
        } finally {
            Object.assign(el.style, originalStyles);
        }
    };

    return { exportPdf };
}
